### ISSUE TITLE
Demo App setup: ERR ERROR: syntax error

### ISSUE THREAD

**Issue by dbaroncelli** [dosco/graphjin#173]
I tried to run the setup for the Demo App
https://graphjin.com/docs/intro#try-the-demo-app

after running:
`docker-compose run api db:setup`

at the end I get this error:
```
INF    mutation {   	comment(insert: $data) {   		id   	}   }
ERR ERROR: syntax error at or near ""_sg_input"" (SQLSTATE 42601)
```

full output:
```
MYSHELL> docker-compose run api db:setup
Creating network "webshop_default" with the default driver
Creating webshop_db_1 ... done
Creating webshop_api_run ... done
INF created database: webshop_development
INF 2021-01-13 16:53:44 executing 1_users.sql up
-- Write your migrate up statements here

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    full_name character varying NOT NULL,
    phone character varying,
    avatar character varying,
    email character varying NOT NULL DEFAULT ''::character varying,
    encrypted_password character varying NOT NULL DEFAULT ''::character varying,
    reset_password_token character varying,
    reset_password_sent_at timestamp without time zone,
    remember_created_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX index_users_on_email ON users(email text_ops);
CREATE UNIQUE INDEX index_users_on_reset_password_token ON users(reset_password_token text_ops);

INF 2021-01-13 16:53:44 executing 2_products.sql up
-- Write your migrate up statements here

CREATE TABLE products (
    id BIGSERIAL PRIMARY KEY,
    name text CHECK (length(name) > 1 AND length(name) < 50),
    description text CHECK (length(name) > 1 AND length(name) < 200),

    -- tsv column is used by full-text search
    tsv tsvector GENERATED ALWAYS 
        AS (to_tsvector('english', name) || to_tsvector('english', description)) STORED,

    tags  text[],  

    category_ids  bigint[] NOT NULL        
        CHECK (cardinality(category_ids) > 0 AND cardinality(category_ids) < 10),

    price           numeric(7,2),
    user_id         bigint REFERENCES users(id),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX index_products_on_tsv ON products USING GIN (tsv tsvector_ops);
CREATE INDEX index_products_on_user_id ON products(user_id int8_ops);

INF 2021-01-13 16:53:44 executing 3_customers.sql up
-- Write your migrate up statements here

CREATE TABLE customers (
    id BIGSERIAL PRIMARY KEY,
    full_name character varying NOT NULL,
    phone character varying,
    stripe_id character varying,
    email character varying NOT NULL DEFAULT ''::character varying,
    encrypted_password character varying NOT NULL DEFAULT ''::character varying,
    reset_password_token character varying,
    reset_password_sent_at timestamp without time zone,
    remember_created_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX index_customers_on_email ON customers(email text_ops);
CREATE UNIQUE INDEX index_customers_on_reset_password_token ON customers(reset_password_token text_ops);

INF 2021-01-13 16:53:44 executing 4_purchases.sql up
-- Write your migrate up statements here

CREATE TABLE purchases (
    id BIGSERIAL PRIMARY KEY,
    customer_id bigint REFERENCES customers(id),
    product_id bigint REFERENCES products(id),
    quantity integer,
    returned_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX index_purchases_on_customer_id ON purchases(customer_id int8_ops);
CREATE INDEX index_purchases_on_product_id ON purchases(product_id int8_ops);

INF 2021-01-13 16:53:44 executing 5_notifications.sql up
-- Write your migrate up statements here

CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    key character varying,
    subject_type character varying,
    subject_id bigint,
    user_id bigint REFERENCES users(id),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

-- Indices -------------------------------------------------------

CREATE INDEX index_notifications_on_subject_id ON notifications(subject_id int8_ops);
CREATE INDEX index_notifications_on_user_id ON notifications(user_id int8_ops);

INF 2021-01-13 16:53:44 executing 6_categories.sql up
-- Write your migrate up statements here

CREATE TABLE categories (
  id BIGSERIAL PRIMARY KEY,

  name          text NOT NULL           CHECK (length(name) < 100),
  description   text                    CHECK (length(description) < 300),

  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone NOT NULL
);

INF 2021-01-13 16:53:44 executing 7_comments.sql up
-- Write your migrate up statements here

CREATE TABLE comments (
    id BIGSERIAL PRIMARY KEY,
    body text CHECK (length(body) > 1 AND length(body) < 200),

    product_id     bigint REFERENCES products(id),
    user_id         bigint REFERENCES users(id),
    reply_to_id     bigint REFERENCES comments(id),

    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

INF 2021-01-13 16:53:44 executing 8_chats.sql up
-- Write your migrate up statements here

CREATE TABLE chats (
    id BIGSERIAL PRIMARY KEY,
    body text,

    reply_to_id     bigint[],

    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

INF migration done
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		user(insert: $data) { 			id 	} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  	mutation { 		customer(insert: $data) { 			id 		} 	}
INF  mutation {   categories(insert: $categories) {     id   } }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	product(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	purchase(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
INF    mutation {   	notification(insert: $data) {   		id   	}   }
{
  "body": "Fact contribution foundation occur break finance remove approval deliver alter.",
  "created_at": "now",
  "product": {
    "connect": {
      "id": 16
    }
  },
  "updated_at": "now",
  "user": {
    "connect": {
      "id": 2
    }
  }
}
INF    mutation {   	comment(insert: $data) {   		id   	}   }
{
  "body": "Land instance find wait construct examine hang month bet expand.",
  "comment": {
    "connect": {
      "id": 1
    },
    "find": "children"
  },
  "created_at": "now",
  "product": {
    "connect": {
      "id": 26
    }
  },
  "updated_at": "now",
  "user": {
    "connect": {
      "id": 3
    }
  }
}
INF    mutation {   	comment(insert: $data) {   		id   	}   }
ERR ERROR: syntax error at or near ""_sg_input"" (SQLSTATE 42601)
```

**Comment by dosco** [comment]
Seems to be fixed in the latest update

```
~ ⟩ cd graphjin
~ ⟩ git pull --rebase
~ ⟩ make install

~ ⟩ graphjin new blog
INR created 'blog'
INR created 'blog/Dockerfile'
INR created 'blog/docker-compose.yml'
INR created 'blog/cloudbuild.yaml'
INR created 'blog/config'
INR created 'blog/config/dev.yml'
INR created 'blog/config/prod.yml'
INR created 'blog/config/seed.js'
INR created 'blog/config/migrations'
INR created 'blog/config/migrations/0_init.sql'
INR app 'blog' initialized

~ ⟩ cd blog/
blog ⟩ docker-compose run api db:setup
Creating blog_api_run ... done
INF database exists: blog_development
INF migration done
INF seed script done
```

**Comment by dbaroncelli** [comment]
I have updated the code.
I now get a "docker-compose" execution error.


`SHELL bin> ./graphjin new blog`
INR created 'blog'
INR created 'blog/Dockerfile'
INR created 'blog/docker-compose.yml'
INR created 'blog/cloudbuild.yaml'
INR created 'blog/config'
INR created 'blog/config/dev.yml'
INR created 'blog/config/prod.yml'
INR created 'blog/config/seed.js'
INR created 'blog/config/migrations'
INR created 'blog/config/migrations/0_init.sql'
INR app 'blog' initialized

`SHELL bin> cd blog`
`SHELL blog> docker-compose run api db:setup`
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[43469] Failed to execute script docker-compose

**Comment by dbaroncelli** [comment]
sorry, my fault
Docker wasn't running
