### ISSUE TITLE
webui: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by bmartel** [dosco/graphjin#236]
### What version of GraphJin are you using? `graphjin version`

v0.16.77

### Have you tried reproducing the issue with the latest release?

Occurs in latest (v0.16.77 at time of this writing)

### What is the hardware spec (RAM, OS)?

OS: Manjaro Linux x86_64
Host: ThinkPad X1 Extreme 2nd
Kernel: 5.9.16-1-MANJARO
CPU: Intel i7-9750H (12) @ 4.500GHz
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q
GPU: Intel UHD Graphics 630
Memory: 31756MiB

### Steps to reproduce the issue (config used to run GraphJin).

Follow documentations get started blog example with the generated users example.

https://github.com/dosco/graphjin/wiki/Quick-Start#2-create-new-api

### Expected behaviour and actual result.

**Expected:**

Should produce a working web ui at http://localhost:8080 to expose the sample users query and documentation explorer.

**Actual:**

![image](https://user-images.githubusercontent.com/2242258/120715802-c4219c00-c48a-11eb-8a39-c52dfa3f80d2.png)

```
api_1  | 2021/06/03 21:35:25 http: panic serving 172.20.0.1:33556: runtime error: invalid memory address or nil pointer
dereference
api_1  | goroutine 164 [running]:
api_1  | net/http.(*conn).serve.func1(0xc009784000)
api_1  |        /usr/local/go/src/net/http/server.go:1824 +0x153
api_1  | panic(0x13eba40, 0x2e39970)
api_1  |        /usr/local/go/src/runtime/panic.go:971 +0x499
api_1  | github.com/dosco/graphjin/serv/internal/auth.WithAuth.func1(0x241b908, 0xc00975a480, 0xc009786000)
api_1  |        /app/serv/internal/auth/auth.go:174 +0x5a
api_1  | net/http.HandlerFunc.ServeHTTP(0xc00934d200, 0x241b908, 0xc00975a480, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2069 +0x44
api_1  | github.com/rs/cors.(*Cors).Handler.func1(0x241b908, 0xc00975a480, 0xc009786000)
api_1  |        /app/vendor/github.com/rs/cors/cors.go:219 +0x1b9
api_1  | net/http.HandlerFunc.ServeHTTP(0xc0044b4560, 0x241b908, 0xc00975a480, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2069 +0x44
api_1  | github.com/dosco/graphjin/serv/internal/etags.Handler.func1(0x241e188, 0xc0092448c0, 0xc009786000)
api_1  |        /app/serv/internal/etags/etag.go:56 +0x1ce
api_1  | net/http.HandlerFunc.ServeHTTP(0xc0044b4580, 0x241e188, 0xc0092448c0, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2069 +0x44
api_1  | github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /app/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x22d
api_1  | net/http.HandlerFunc.ServeHTTP(0xc00934d3e0, 0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2069 +0x44
api_1  | net/http.(*ServeMux).ServeHTTP(0xc009333f40, 0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2448 +0x1ad
api_1  | github.com/dosco/graphjin/serv.setServerHeader.func1(0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /app/serv/serv.go:210 +0x131
api_1  | net/http.HandlerFunc.ServeHTTP(0xc002320318, 0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2069 +0x44
api_1  | net/http.serverHandler.ServeHTTP(0xc002074620, 0x241e038, 0xc002074ee0, 0xc009786000)
api_1  |        /usr/local/go/src/net/http/server.go:2887 +0xa3
api_1  | net/http.(*conn).serve(0xc009784000, 0x2422bd8, 0xc00935c8c0)
api_1  |        /usr/local/go/src/net/http/server.go:1952 +0x8cd
api_1  | created by net/http.(*Server).Serve
api_1  |        /usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by dosco** [comment]
Did some refactoring yesterday to add more logging to auth and introduced this bug. I need to add more tests around the auth package.

**Comment by bmartel** [comment]
That fixes the problem, it is now working correctly thank you!

![image](https://user-images.githubusercontent.com/2242258/120840003-4794c900-c52f-11eb-958b-d991ebbb71a4.png)
